Type: AWS::DynamoDB::Table
Properties:
  TableName: ${self:custom.DatabaseTable.PetsTable}
  BillingMode: PAY_PER_REQUEST
  AttributeDefinitions:
    - AttributeName: petId
      AttributeType: S
  KeySchema:
    - AttributeName: petId
      KeyType: HASH
