Type: AWS::DynamoDB::Table
Properties:
  TableName: ${self:custom.DatabaseTable.PetsTable}
  BillingMode: PAY_PER_REQUEST
  AttributeDefinitions:
    - AttributeName: petId
      AttributeType: S
    - AttributeName: owner
      AttributeType: S
  KeySchema:
    - AttributeName: petId
      KeyType: HASH
  GlobalSecondaryIndexes:
    - IndexName: ownerEmail
      KeySchema:
        - AttributeName: owner
          KeyType: HASH
      Projection:
        ProjectionType: ALL
