createPet:
  handler: src/handlers/createPet.handler
  events:
    - http:
        path: /pet
        method: POST
        authorizer:
          arn: ${self:custom.pets-authorizer}
getAllPets:
  handler: src/handlers/getAllPets.handler
  events:
    - http:
        path: /pets
        method: GET
        authorizer:
          arn: ${self:custom.pets-authorizer}
getPet:
  handler: src/handlers/getPet.handler
  events:
    - http:
        path: /pet/${id}
        method: GET
updatePet:
  handler: src/handlers/updatePet.handler
  events:
    - http:
        path: /pet/{id}
        method: PATCH
        authorizer:
          arn: ${self:custom.pets-authorizer}
deletePet:
  handler: src/handlers/deletePet.handler
  events:
    - http:
        path: /pet/{id}
        method: DELETE
        authorizer:
          arn: ${self:custom.pets-authorizer}
uploadPetPhoto:
  handler: src/handlers/uploadPetPhoto.handler
  events:
    - http:
        path: pet/uploadPetPhoto/
        method: POST
        authorizer:
          arn: ${self:custom.pets-authorizer}
