TrackaPetsMailQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:custom.TrackaPetsMailQueue.name}
Outputs:
  TrackaPetsMailQueueArn:
    Value: ${self:custom.TrackaPetsMailQueue.arn}
    Export:
      Name: ${self:custom.TrackaPetsMailQueue.name}-Arn
  TrackaPetsMailQueueUrl:
    Value: ${self:custom.TrackaPetsMailQueue.url}
    Export:
      Name: ${self:custom.TrackaPetsMailQueue.name}-Url
