- Effect: 'Allow'
  Action:
    - 'dynamodb:PutItem'
    - 'dynamodb:GetItem'
    - 'dynamodb:DeleteItem'
    - 'dynamodb:UpdateItem'
    - 'dynamodb:Scan'
    - 'dynamodb:Query'
  Resource:
    - arn:aws:dynamodb:${self:custom.UserId}:table/${self:custom.DatabaseTable.PetsTable}
# Role for ownerEmail indexing
- Effect: Allow
  Action:
    - 'dynamodb:Query'
  Resource:
    - arn:aws:dynamodb:${self:custom.UserId}:table/${self:custom.DatabaseTable.PetsTable}/index/ownerEmail
- Effect: Allow
  Action:
    - 's3:PutObject'
  Resource: arn:aws:s3:::${self:custom.TrackaPetsBucket.name}/images/*
# Send email
- Effect: 'Allow'
  Action:
    - ses:SendEmail
  Resource: arn:aws:ses:*
